"""Shared wav2vec2/MMS-300M architecture config (24-layer, 1024-dim fairseq Wav2Vec2Model),
identical for both the original and anti-deepfake-post-trained checkpoints below -- verified by
inspecting both checkpoints' cfg['model'] / state_dict shapes."""

MMS_CONFIGS = {
    "_name": "wav2vec2",
    "extractor_mode": "layer_norm",
    "encoder_layers": 24,
    "encoder_embed_dim": 1024,
    "encoder_ffn_embed_dim": 4096,
    "encoder_attention_heads": 16,
    "activation_fn": "gelu",
    "dropout": 0.0,
    "attention_dropout": 0.0,
    "activation_dropout": 0.0,
    "encoder_layerdrop": 0.0,
    "dropout_input": 0.0,
    "dropout_features": 0.0,
    "final_dim": 768,
    "layer_norm_first": True,
    "conv_feature_layers": "[(512, 10, 5)] + [(512, 3, 2)] * 4 + [(512,2,2)] + [(512,2,2)]",
    "conv_bias": True,
    "logit_temp": 0.1,
    "quantize_targets": True,
    "quantize_input": False,
    "same_quantizer": False,
    "target_glu": False,
    "feature_grad_mult": 1.0,
    "quantizer_depth": 1,
    "quantizer_factor": 3,
    "latent_vars": 320,
    "latent_groups": 2,
    "latent_dim": 0,
    "mask_length": 10,
    "mask_prob": 0.65,
    "mask_selection": "static",
    "mask_other": 0.0,
    "no_mask_overlap": False,
    "mask_min_space": 1,
    "num_negatives": 100,
    "negatives_from_everywhere": False,
    "cross_sample_negatives": 0,
    "codebook_negatives": 0,
    "conv_pos": 128,
    "conv_pos_groups": 16,
    "latent_temp": [2.0, 0.1, 0.999995],
}

GLOBAL_OUTPUT_DIM = 1024
